sudo: false
language: cpp
os:
    - linux

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
env:
        - CC=gcc-6 && CXX=g++-6

script:
    - cmake .
    - cmake --build . -- -j2
